version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"           # Changed from 8080
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:9444"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=admin@unilog.company"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"        # Changed from 8080:8080
      - "9444:9444"    # HTTPS
      - "8080:8080"    # Dashboard (changed from 9001)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
      - ./logs/traefik:/var/log/traefik
    networks:
      - web
    restart: unless-stopped

  shipping-calculator:
    build: .
    networks:
      - web
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      # FastAPI configuration
      - "traefik.http.routers.api.rule=Host(`api.calculator.unilog.company`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=8001"
      # Streamlit configuration
      - "traefik.http.routers.streamlit.rule=Host(`calculator.unilog.company`)"
      - "traefik.http.routers.streamlit.entrypoints=websecure"
      - "traefik.http.routers.streamlit.tls=true"
      - "traefik.http.routers.streamlit.tls.certresolver=myresolver"
      - "traefik.http.services.streamlit.loadbalancer.server.port=8502"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web:
    driver: bridge

volumes:
  traefik-certificates:
